table 'Data Sales Adidas'
	lineageTag: 55447416-aedc-4229-ab68-1244e4a0b38e

	column Retailer
		dataType: string
		lineageTag: 6a510afc-c809-4589-a0f5-03303082e602
		summarizeBy: none
		sourceColumn: Retailer

		annotation SummarizationSetBy = Automatic

	column 'Retailer ID'
		dataType: int64
		formatString: 0
		lineageTag: 61a7393a-395b-4d74-a658-769913f9c6f3
		summarizeBy: count
		sourceColumn: Retailer ID

		annotation SummarizationSetBy = Automatic

	column 'Invoice Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9d3911b-1612-425a-8c25-d8ad2b72969f
		summarizeBy: none
		sourceColumn: Invoice Date

		variation Variation
			isDefault
			relationship: 5e7cf2f0-a49b-40c3-92fd-018517c252ba
			defaultHierarchy: LocalDateTable_4aff2bea-f5f8-4a7e-90cf-fa595f43a9a5.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Region
		dataType: string
		lineageTag: 8faa9e0f-3d11-42ea-94f8-6c0b31add512
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a72ae24c-112e-44e5-8ff2-cd996bb2d319
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 36e21ebc-42c1-4427-a36a-76510fe05a0f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 10c10ac8-bfa2-47c9-8269-d4ec6fa8065d
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Price per Unit'
		dataType: double
		lineageTag: fd1358e8-5ec6-4ea9-b751-9cd3cccc29a8
		summarizeBy: sum
		sourceColumn: Price per Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: a8e97622-93dd-457f-9375-a1529d30f126
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Total Sales'
		dataType: double
		lineageTag: f95cc9c3-6b34-4402-a24a-cba85734d920
		summarizeBy: sum
		sourceColumn: Total Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Operating Profit'
		dataType: double
		lineageTag: e85eac67-f806-4df2-9064-06a7a09eb8b9
		summarizeBy: sum
		sourceColumn: Operating Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Operating Margin'
		dataType: double
		lineageTag: 473486a8-002c-44c0-b4fd-7aad0b1a30d2
		summarizeBy: sum
		sourceColumn: Operating Margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Method'
		dataType: string
		lineageTag: cfd24d03-35b1-48f4-8773-da42a3c2aa9c
		summarizeBy: none
		sourceColumn: Sales Method

		annotation SummarizationSetBy = Automatic

	partition 'Data Sales Adidas' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\alexa\OneDrive\Documents\A2\DataSet\DataSet\ProjetBIA2\Adidas US Sales Datasets.xlsx"), null, true),
				    #"Data Sales Adidas_Sheet" = Source{[Item="Data Sales Adidas",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(#"Data Sales Adidas_Sheet", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Retailer", type text}, {"Retailer ID", Int64.Type}, {"Invoice Date", type date}, {"Region", type text}, {"State", type text}, {"City", type text}, {"Product", type text}, {"Price per Unit", type number}, {"Units Sold", Int64.Type}, {"Total Sales", type number}, {"Operating Profit", type number}, {"Operating Margin", type number}, {"Sales Method", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

