table nike_2020_04_13
	lineageTag: 6183b25d-96cc-482a-9c8d-e3e8fc0316c7

	column URL
		dataType: string
		lineageTag: 6c8ef7d8-8cca-44a9-9a15-c60a4970fef2
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: f27b58c2-6217-4f95-b3d1-dc08c65eb8ed
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 3d1cf96c-bef8-4d0e-8193-8ff4db8ac2ce
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Listing Price'
		dataType: int64
		formatString: 0
		lineageTag: 57724c53-f594-413d-9718-18c0a68198b5
		summarizeBy: sum
		sourceColumn: Listing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 2dd9b45e-2ca1-4903-8d9a-07358586aa2e
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: int64
		formatString: 0
		lineageTag: a453270d-adec-4aab-ac5e-5a9bc1da0444
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 9eb0a344-858b-40d3-ba82-9cc119131aa5
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 550028f0-8b1a-434e-8c1e-d39059050969
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: string
		lineageTag: fedc4404-0521-451a-b317-990a7b4c39d6
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column Reviews
		dataType: int64
		formatString: 0
		lineageTag: adb8dbbe-6bf9-4830-b5a4-380ac8f91738
		summarizeBy: sum
		sourceColumn: Reviews

		annotation SummarizationSetBy = Automatic

	column Images
		dataType: string
		lineageTag: dc263868-e7c8-4a63-9ba4-19d6b2f98780
		summarizeBy: none
		sourceColumn: Images

		annotation SummarizationSetBy = Automatic

	column 'Last Visited'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1dffde90-5b41-4fae-ae81-03945674c9f9
		summarizeBy: none
		sourceColumn: Last Visited

		variation Variation
			isDefault
			relationship: eee6daf2-a675-4bea-b39e-8308bcee3052
			defaultHierarchy: LocalDateTable_09bb1d4e-4c3e-41fe-ad34-5d5fd29373f3.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	partition nike_2020_04_13 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\alexa\OneDrive\Documents\A2\DataSet\DataSet\ProjetBIA2\nike_2020_04_13.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"URL", type text}, {"Product Name", type text}, {"Product ID", type text}, {"Listing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Discount", Int64.Type}, {"Brand", type text}, {"Description", type text}, {"Rating", type text}, {"Reviews", Int64.Type}, {"Images", type text}, {"Last Visited", type datetime}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

